# Generated by Django 3.2.16 on 2023-01-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_physician',
            field=models.BooleanField(default=False),
        ),
    ]
