# Generated by Django 3.2.16 on 2023-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230111_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_physician',
            field=models.BooleanField(default=False),
        ),
    ]
