# Generated by Django 3.2.16 on 2023-01-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doc_email',
            field=models.EmailField(default='none@email.com', max_length=254),
        ),
    ]
