# Generated by Django 3.2.16 on 2023-01-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230113_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='none@email.com', max_length=248),
        ),
    ]
